# This is a basic workflow to help you get started with Actions

name: First workflow

# Controls when the workflow will run, for this we can manually trigger the jobs
on: workflow_dispatch 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  first-job:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print greeting
        run: echo Hello, world!
      - name: Print goodbye
        run: echo Bye, bye!

